# Generated by Django 3.1.4 on 2021-04-01 16:22

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Names',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('all_names', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
    ]
